// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  colorchanger: dynamic(() => import("./Colorchanger")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  purchase_button: dynamic(() => import("./PurchaseButton")),
  switch_playground: dynamic(() => import("./SwitchPlayground")),
};
